### ISSUE TITLE
ComputeNormal是不是有问题啊

### ISSUE THREAD

**Issue by BuLiangRenDarkStar** [Ymiku/Automic-LOD#3]
Vector3 p1 = vertex[1].pos-vertex[0].pos;
Vector3 p2 = vertex[1].pos-vertex[0].pos;
normal = Vector3.Cross (p1,p2).normalized;
 p2为什么和p1是同一个向量，Vector3 p2 = vertex[2].pos-vertex[0].pos;

**Comment by Ymiku** [comment]
改了
